### ISSUE TITLE
installation fails if already installed in `src`

### ISSUE THREAD

**Issue by tcurdt** [pote/gpm#66] opened 2015-02-15 17:54 UTC
$ find .godeps
    .godeps
    .godeps/bin
    .godeps/pkg
    .godeps/src

    $ cat Godeps 
    github.com/golang/glog
    github.com/gorilla/mux
    golang.org/x/oauth2

    $ echo $GOPATH
    /Users/tcurdt/..../myproject/.godeps:/Users/tcurdt/..../myproject

    $ gpm install
    >> Getting package github.com/golang/glog
    >> Getting package github.com/gorilla/mux
    >> Getting package golang.org/x/oauth2
    >> Setting github.com/golang/glog to version 
    >> Setting golang.org/x/oauth2 to version 
    /usr/local/bin/gpm: line 66: cd: /Users/tcurdt/..../myproject/.godeps/src/github.com/golang/glog: No such file or directory
    >> Setting github.com/gorilla/mux to version 
    /usr/local/bin/gpm: line 66: cd:  /Users/tcurdt/..../myproject/.godeps/src/golang.org/x/oauth2: No such file or directory
    /usr/local/bin/gpm: line 66: cd:  /Users/tcurdt/..../myproject/.godeps/src/github.com/gorilla/mux: No such file or directory
    >> Building package github.com/golang/glog
    >> Building package github.com/gorilla/mux
    >> Building package golang.org/x/oauth2
    >> All Done

    $ find .godeps
    .godeps
    .godeps/bin
    .godeps/pkg
    .godeps/src

**Comment by tcurdt** [comment] 2015-02-15 17:59
Turns out the problem was that I still had the them in `src`. This should be caught and give a proper error message.

**Comment by exu** [comment] 2015-10-08 03:42
I have the same problem, my quick workaround helps with it
```
export GOPATH=$(pwd)/.godeps:$(pwd) 
```

**Comment by pote** [comment] 2016-01-25 15:38
I can't reproduce the error with the latest gpm, closing the issue unless anybody can provide a reproducible report (if so, please reopen).

It's worth noting that the `Godeps` file is intended to keep revisions of each package, otherwise the HEAD version of each package will be installed (which is the same as simply running `go get`!)

**Closed by pote** 2016-01-25 15:38 UTC
