### ISSUE TITLE
Dependency binaries not building?

### ISSUE THREAD

**Issue by leeola** [pote/gpm#50] opened 2014-09-23 15:56 UTC
I have a project with a dependency on `github.com/smartystreets/goconvey`, but when gpm installs the dependency the goconvey binary is not built. On the flipside, if you use `go get github.com/smartystreets/goconvey` the binary is created without issue.

So, with that said, is this intentional? And if so, is there a trick to getting the binary created as part of the gpm dependency resolution process?

**Comment by pre** [comment] 2015-03-24 13:28
I ran into this very issue with goconvey. 

Any best practices how to `gpm install` to get both goconvey sources AND `bin/goconvey` ?

I'm looking for a solution that would work across a team, so that there wouldn't be a requirement such as "you need this one extra `go get` after `gpm install`" :)

**Comment by leeola** [comment] 2015-03-24 18:19
Well as pote said, `go install foo` works quite well. I'm not sure what you could do for your Team (if you want to distribute plugins or not), but my thought process originally was to have a way to signal libraries that needed binaries, and automatically run `go install foo` after the library was checked out by `gpm`. This signal could be a `Godeps.bin` file _(a special file, for just binaries)_, or a syntax within the normal Godeps file that you make up.

Depending on how many binaries you need though, a plugin may be overkill - as was my experience. I just use `go install foo`. :)

**Comment by pote** [comment] 2015-03-24 18:27
Well, actually gpm starting running `go install` for all dependencies [not too long ago](https://github.com/pote/gpm/blob/master/bin/gpm#L77-L80)! :)

This really depends a lot on how people install things and what their setup is, what does your GOPATH look like @pre ? what version of gpm are you on? Do you install goconvey in the same place you install your project dependencies? go install has some quirks on binary creation depending on GOPATH setup.

**Comment by pre** [comment] 2015-03-25 15:00
gpm version 1.3.2

I use gvp to get project-independent packages. Packages are installed under `project_dir/.godeps`
I have `github.com/smartystreets/goconvey/convey  master` in `Godeps`.

After `gpm install` everything else is installed except `.godeps/bin/goconvey`. When I manually run `go install github.com/smartystreets/goconvey`, then `.godeps/bin/goconvey` will be created. 

Problem is reproduceable by first removing the deps with `rm -fr .godeps` and redoing the steps above.

As a workaround, I created a Makefile task:

```
deps:
  bash -c "source gvp && gpm install && go get github.com/smartystreets/goconvey"
```

It's not optimal, but since goconvey is currently the only dependency with binaries, this allows installing all the dependencies with one command `make deps`.

**Comment by pre** [comment] 2015-03-25 15:05
I'M SORRY GUISE... 

Right after posting the comment I saw the typo there, should have `github.com/smartystreets/goconvey` in `Godeps` (had one extra `/convey` there).

K THX BAI

**Comment by pre** [comment] 2015-03-25 15:06
(it is still funny that the dependency was otherwise installed without errors using the incorrect path, only the binaries went missing....... )

**Comment by pote** [comment] 2015-03-25 17:30
it definitely is funky, gpm has [flags](https://github.com/pote/gpm/blob/master/bin/gpm#L3) set to ensure it aborts execution if any of the commands return a non-success status code.

The extra `/convey`  is making go install compile the `convey` package into `$GOPATH/pkg` and ignore everything else, meaning a successful exit code and no errors in gpm, it makes sense I guess.

 I'm glad the problem it's fixed for you! closing the issue again, thanks everyone! :)

**Closed by pote** 2015-03-25 17:30 UTC
